'use client';

import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    // Header
    aboutUs: 'About Us',
    admin: 'Admin',
    signIn: 'Sign In',
    dashboard: 'Dashboard',
    signOut: 'Sign Out',
    deliverTo: 'Deliver to',
    setAddress: 'Select your address',
    // Home
    heroTitle: 'Healthy &',
    heroTitle2: 'Delicious.',
    heroSubtitle: 'Experience the crunch. Premium oatbites crafted with love, care, and the finest organic ingredients.',
    shopNow: 'Shop Now',
    featuredOatbites: 'Featured Oatbites',
    viewAllProducts: 'View All Products',
    addToCart: 'Add to Cart',
    inCart: 'In Cart',
    // Dashboard
    customer: 'Customer',
    yourOrders: 'Your Orders',
    noOrders: "You haven't placed any orders yet.",
    startShopping: 'Start Shopping',
    editProfile: 'Edit Profile',
    saveChanges: 'Save Changes',
    saving: 'Saving...',
    profileUpdated: 'Profile updated successfully!',
    phone: 'Phone Number',
    address: 'Address',
    name: 'Full Name',
    email: 'Email',
    cancel: 'Cancel',
    // Products
    products: 'Products',
    searchProducts: 'Search products...',
    allProducts: 'All Products',
    outOfStock: 'Out of Stock',
    // Checkout
    checkout: 'Checkout',
    shippingDetails: 'Shipping Details',
    fullName: 'Full Name',
    streetAddress: 'Street Address',
    city: 'City',
    state: 'State',
    pincode: 'Pincode',
    orderSummary: 'Order Summary',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    free: 'Free',
    total: 'Total',
    payNow: 'Pay Now',
    // Auth
    welcomeBack: 'Welcome Back',
    signInSubtitle: 'Sign in to your Oatbites account',
    emailAddress: 'Email Address',
    password: 'Password',
    signingIn: 'Signing in...',
    or: 'OR',
    continueWithGoogle: 'Continue with Google',
    signUpWithGoogle: 'Sign up with Google',
    noAccount: "Don't have an account?",
    signUp: 'Sign Up',
    createAccount: 'Create Account',
    createAccountSubtitle: 'Join Oatbites to start shopping',
    creatingAccount: 'Creating account...',
    hasAccount: 'Already have an account?',
    men: 'Men',
    women: 'Women',
    // Product Detail
    backToProducts: '← Back to Products',
    lowStock: 'Only {n} left — Hurry!',
    inStock: 'In Stock',
    notifyMe: '🔔 Notify Me When Available',
    youllBeNotified: "🔔 You'll Be Notified",
    loginToNotify: 'Please login to get notified',
    notificationRemoved: 'Notification removed',
    somethingWentWrong: 'Something went wrong',
    whyYoullLoveIt: "Why you'll love it:",
    organicIngredients: '100% Organic Ingredients',
    sustainablySourced: 'Sustainably Sourced',
    noPreservatives: 'No Artificial Preservatives',
    // Reviews
    ratingsReviews: 'Ratings & Reviews',
    review: 'review',
    reviews: 'reviews',
    writeReview: '✍️ Write a Review',
    editReview: '✏️ Edit Review',
    yourRating: 'Your Rating:',
    reviewPlaceholder: 'Share your experience with this product... (optional)',
    submitReview: 'Submit Review',
    updateReview: 'Update Review',
    submitting: 'Submitting...',
    signInToReview: 'Sign in to write a review after purchasing this product.',
    purchaseToReview: 'Purchase this product to leave a review.',
    noReviews: 'No reviews yet. Be the first to review this product!',
    you: 'You',
    loadingReviews: 'Loading reviews...',
    pleaseSelectRating: 'Please select a rating',
    // Push Notifications
    enableNotifPrompt: 'Enable notifications for order updates and back-in-stock alerts?',
    enable: 'Enable',
    notNow: 'Not Now',
    notificationsEnabled: 'Notifications enabled!',
    // Dashboard
    myOrders: 'MY ORDERS',
    accountSettings: 'ACCOUNT SETTINGS',
    profileInfo: 'Profile Information',
    manageAddresses: 'Manage Addresses',
    notifications: 'Notifications',
    payments: 'PAYMENTS',
    giftCards: 'Gift Cards',
    savedUpi: 'Saved UPI',
    savedCards: 'Saved Cards',
    hello: 'Hello,',
    personalInfo: 'Personal Information',
    edit: 'Edit',
    yourGender: 'Your Gender',
    male: 'Male',
    female: 'Female',
    mobileNumber: 'Mobile Number',
    save: 'SAVE',
    savingUpper: 'SAVING...',
    addNewAddress: 'ADD A NEW ADDRESS',
    addressType: 'Address Type',
    home: 'Home',
    work: 'Work',
    saveAndDeliver: 'SAVE AND DELIVER HERE',
    delete: 'Delete',
    locality: 'Locality',
    pushNotifications: 'Push Notifications',
    stayUpdated: 'Stay Updated!',
    pushDescription: 'Get instant alerts for order shipping updates and when your favorite out-of-stock items are back.',
    enableNotifications: 'ENABLE NOTIFICATIONS',
    enableInBrowser: 'Please enable notifications in your browser settings.',
    noGiftCards: 'No Gift Cards found',
    noGiftCardsDesc: "You haven't added any gift cards yet.",
    addGiftCard: 'ADD A GIFT CARD',
    noSavedUpi: 'No Saved UPI IDs',
    noSavedUpiDesc: 'Save your UPI IDs for faster payments.',
    noSavedCards: 'No Saved Cards',
    noSavedCardsDesc: 'You can save your Credit/Debit cards for a seamless checkout experience.',
    orderedOn: 'Ordered on',
    noOrdersFound: 'No orders found.',
    // Order Confirmation
    orderConfirmed: 'Order Confirmed!',
    thankYou: 'Thank you for shopping with Oatbites by SEJ',
    orderId: 'Order ID',
    orderReceivedMsg: "We've received your order and are preparing it with care. You can track your order status from your dashboard.",
    viewMyOrders: 'View My Orders',
    continueShopping: 'Continue Shopping',
    loading: 'Loading...',
    // Footer
    copyright: '© 2026 Oatbites by SEJ. All rights reserved.',
    // Language
    language: 'Language',
  },
  hi: {
    aboutUs: 'हमारे बारे में',
    admin: 'एडमिन',
    signIn: 'साइन इन',
    dashboard: 'डैशबोर्ड',
    signOut: 'साइन आउट',
    deliverTo: 'यहां डिलीवर करें',
    setAddress: 'अपना पता चुनें',
    heroTitle: 'स्वस्थ और',
    heroTitle2: 'स्वादिष्ट।',
    heroSubtitle: 'क्रंच का अनुभव करें। प्यार, देखभाल और बेहतरीन जैविक सामग्री से बने प्रीमियम ओटबाइट्स।',
    shopNow: 'अभी खरीदें',
    featuredOatbites: 'विशेष ओटबाइट्स',
    viewAllProducts: 'सभी उत्पाद देखें',
    addToCart: 'कार्ट में डालें',
    inCart: 'कार्ट में',
    customer: 'ग्राहक',
    yourOrders: 'आपके ऑर्डर',
    noOrders: 'आपने अभी तक कोई ऑर्डर नहीं दिया है।',
    startShopping: 'खरीदारी शुरू करें',
    editProfile: 'प्रोफ़ाइल संपादित करें',
    saveChanges: 'बदलाव सहेजें',
    saving: 'सहेज रहे हैं...',
    profileUpdated: 'प्रोफ़ाइल सफलतापूर्वक अपडेट हुई!',
    phone: 'फ़ोन नंबर',
    address: 'पता',
    name: 'पूरा नाम',
    email: 'ईमेल',
    cancel: 'रद्द करें',
    products: 'उत्पाद',
    searchProducts: 'उत्पाद खोजें...',
    allProducts: 'सभी उत्पाद',
    outOfStock: 'स्टॉक में नहीं',
    checkout: 'चेकआउट',
    shippingDetails: 'शिपिंग विवरण',
    fullName: 'पूरा नाम',
    streetAddress: 'सड़क का पता',
    city: 'शहर',
    state: 'राज्य',
    pincode: 'पिनकोड',
    orderSummary: 'ऑर्डर सारांश',
    subtotal: 'उपकुल',
    shipping: 'शिपिंग',
    free: 'मुफ़्त',
    total: 'कुल',
    payNow: 'अभी भुगतान करें',
    welcomeBack: 'फिर से स्वागत है',
    signInSubtitle: 'अपने ओटबाइट्स खाते में साइन इन करें',
    emailAddress: 'ईमेल पता',
    password: 'पासवर्ड',
    signingIn: 'साइन इन हो रहा है...',
    or: 'या',
    continueWithGoogle: 'Google से जारी रखें',
    signUpWithGoogle: 'Google से साइन अप',
    noAccount: 'खाता नहीं है?',
    signUp: 'साइन अप',
    createAccount: 'खाता बनाएं',
    createAccountSubtitle: 'खरीदारी शुरू करने के लिए ओटबाइट्स जॉइन करें',
    creatingAccount: 'खाता बनाया जा रहा है...',
    hasAccount: 'पहले से खाता है?',
    men: 'पुरुष',
    women: 'महिला',
    backToProducts: '← उत्पादों पर वापस',
    lowStock: 'केवल {n} बचे — जल्दी करें!',
    inStock: 'स्टॉक में',
    notifyMe: '🔔 उपलब्ध होने पर सूचित करें',
    youllBeNotified: '🔔 आपको सूचित किया जाएगा',
    loginToNotify: 'सूचना के लिए लॉगिन करें',
    notificationRemoved: 'सूचना हटाई गई',
    somethingWentWrong: 'कुछ गलत हो गया',
    whyYoullLoveIt: 'आप इसे क्यों पसंद करेंगे:',
    organicIngredients: '100% जैविक सामग्री',
    sustainablySourced: 'टिकाऊ स्रोत',
    noPreservatives: 'कोई कृत्रिम परिरक्षक नहीं',
    ratingsReviews: 'रेटिंग और समीक्षाएँ',
    review: 'समीक्षा',
    reviews: 'समीक्षाएँ',
    writeReview: '✍️ समीक्षा लिखें',
    editReview: '✏️ समीक्षा संपादित करें',
    yourRating: 'आपकी रेटिंग:',
    reviewPlaceholder: 'इस उत्पाद के साथ अपना अनुभव साझा करें... (वैकल्पिक)',
    submitReview: 'समीक्षा सबमिट करें',
    updateReview: 'समीक्षा अपडेट करें',
    submitting: 'सबमिट हो रहा है...',
    signInToReview: 'इस उत्पाद को खरीदने के बाद समीक्षा लिखने के लिए साइन इन करें।',
    purchaseToReview: 'समीक्षा देने के लिए यह उत्पाद खरीदें।',
    noReviews: 'अभी तक कोई समीक्षा नहीं। इस उत्पाद की पहली समीक्षा लिखें!',
    you: 'आप',
    loadingReviews: 'समीक्षाएँ लोड हो रही हैं...',
    pleaseSelectRating: 'कृपया रेटिंग चुनें',
    enableNotifPrompt: 'ऑर्डर अपडेट और बैक-इन-स्टॉक अलर्ट के लिए सूचनाएँ सक्षम करें?',
    enable: 'सक्षम करें',
    notNow: 'अभी नहीं',
    notificationsEnabled: 'सूचनाएँ सक्षम!',
    myOrders: 'मेरे ऑर्डर',
    accountSettings: 'खाता सेटिंग्स',
    profileInfo: 'प्रोफ़ाइल जानकारी',
    manageAddresses: 'पते प्रबंधित करें',
    notifications: 'सूचनाएँ',
    payments: 'भुगतान',
    giftCards: 'गिफ्ट कार्ड',
    savedUpi: 'सहेजा UPI',
    savedCards: 'सहेजे कार्ड',
    hello: 'नमस्ते,',
    personalInfo: 'व्यक्तिगत जानकारी',
    edit: 'संपादित करें',
    yourGender: 'आपका लिंग',
    male: 'पुरुष',
    female: 'महिला',
    mobileNumber: 'मोबाइल नंबर',
    save: 'सहेजें',
    savingUpper: 'सहेज रहे हैं...',
    addNewAddress: 'नया पता जोड़ें',
    addressType: 'पते का प्रकार',
    home: 'घर',
    work: 'कार्यालय',
    saveAndDeliver: 'सहेजें और यहाँ डिलीवर करें',
    delete: 'हटाएँ',
    locality: 'इलाका',
    pushNotifications: 'पुश सूचनाएँ',
    stayUpdated: 'अपडेट रहें!',
    pushDescription: 'ऑर्डर शिपिंग अपडेट और जब आपकी पसंदीदा आउट-ऑफ-स्टॉक वस्तुएँ वापस आएँ तो तुरंत अलर्ट पाएँ।',
    enableNotifications: 'सूचनाएँ सक्षम करें',
    enableInBrowser: 'कृपया अपनी ब्राउज़र सेटिंग्स में सूचनाएँ सक्षम करें।',
    noGiftCards: 'कोई गिफ्ट कार्ड नहीं',
    noGiftCardsDesc: 'आपने अभी तक कोई गिफ्ट कार्ड नहीं जोड़ा है।',
    addGiftCard: 'गिफ्ट कार्ड जोड़ें',
    noSavedUpi: 'कोई सहेजा UPI नहीं',
    noSavedUpiDesc: 'तेज़ भुगतान के लिए अपनी UPI ID सहेजें।',
    noSavedCards: 'कोई सहेजे कार्ड नहीं',
    noSavedCardsDesc: 'सहज चेकआउट अनुभव के लिए अपने क्रेडिट/डेबिट कार्ड सहेजें।',
    orderedOn: 'ऑर्डर किया',
    noOrdersFound: 'कोई ऑर्डर नहीं मिला।',
    orderConfirmed: 'ऑर्डर पुष्टि!',
    thankYou: 'Oatbites by SEJ से खरीदारी के लिए धन्यवाद',
    orderId: 'ऑर्डर आईडी',
    orderReceivedMsg: 'हमने आपका ऑर्डर प्राप्त कर लिया है और इसे सावधानी से तैयार कर रहे हैं। आप अपने डैशबोर्ड से ऑर्डर की स्थिति ट्रैक कर सकते हैं।',
    viewMyOrders: 'मेरे ऑर्डर देखें',
    continueShopping: 'खरीदारी जारी रखें',
    loading: 'लोड हो रहा है...',
    copyright: '© 2026 ओटबाइट्स बाय SEJ। सर्वाधिकार सुरक्षित।',
    language: 'भाषा',
  },
  bn: {
    aboutUs: 'আমাদের সম্পর্কে',
    admin: 'অ্যাডমিন',
    signIn: 'সাইন ইন',
    dashboard: 'ড্যাশবোর্ড',
    signOut: 'সাইন আউট',
    deliverTo: 'এখানে ডেলিভারি দিন',
    setAddress: 'আপনার ঠিকানা নির্বাচন করুন',
    heroTitle: 'স্বাস্থ্যকর ও',
    heroTitle2: 'সুস্বাদু।',
    heroSubtitle: 'ক্রাঞ্চের অভিজ্ঞতা নিন। ভালোবাসা, যত্ন এবং সেরা জৈব উপাদান দিয়ে তৈরি প্রিমিয়াম ওটবাইটস।',
    shopNow: 'এখনই কিনুন',
    featuredOatbites: 'বিশেষ ওটবাইটস',
    viewAllProducts: 'সব পণ্য দেখুন',
    addToCart: 'কার্টে যোগ করুন',
    inCart: 'কার্টে আছে',
    customer: 'গ্রাহক',
    yourOrders: 'আপনার অর্ডার',
    noOrders: 'আপনি এখনও কোনো অর্ডার দেননি।',
    startShopping: 'কেনাকাটা শুরু করুন',
    editProfile: 'প্রোফাইল সম্পাদনা',
    saveChanges: 'পরিবর্তন সংরক্ষণ',
    saving: 'সংরক্ষণ হচ্ছে...',
    profileUpdated: 'প্রোফাইল সফলভাবে আপডেট হয়েছে!',
    phone: 'ফোন নম্বর',
    address: 'ঠিকানা',
    name: 'পুরো নাম',
    email: 'ইমেইল',
    cancel: 'বাতিল',
    products: 'পণ্য',
    searchProducts: 'পণ্য খুঁজুন...',
    allProducts: 'সব পণ্য',
    outOfStock: 'স্টকে নেই',
    checkout: 'চেকআউট',
    shippingDetails: 'শিপিং বিবরণ',
    fullName: 'পুরো নাম',
    streetAddress: 'রাস্তার ঠিকানা',
    city: 'শহর',
    state: 'রাজ্য',
    pincode: 'পিনকোড',
    orderSummary: 'অর্ডার সারাংশ',
    subtotal: 'উপমোট',
    shipping: 'শিপিং',
    free: 'বিনামূল্যে',
    total: 'মোট',
    payNow: 'এখনই পেমেন্ট করুন',
    welcomeBack: 'ফিরে আসুন',
    signInSubtitle: 'আপনার ওটবাইটস অ্যাকাউন্টে সাইন ইন করুন',
    emailAddress: 'ইমেইল ঠিকানা',
    password: 'পাসওয়ার্ড',
    signingIn: 'সাইন ইন হচ্ছে...',
    or: 'অথবা',
    continueWithGoogle: 'Google দিয়ে চালিয়ে যান',
    signUpWithGoogle: 'Google দিয়ে সাইন আপ',
    noAccount: 'অ্যাকাউন্ট নেই?',
    signUp: 'সাইন আপ',
    createAccount: 'অ্যাকাউন্ট তৈরি করুন',
    createAccountSubtitle: 'কেনাকাটা শুরু করতে ওটবাইটস যোগ দিন',
    creatingAccount: 'অ্যাকাউন্ট তৈরি হচ্ছে...',
    hasAccount: 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
    men: 'পুরুষ',
    women: 'মহিলা',
    backToProducts: '← পণ্যে ফিরে যান',
    lowStock: 'মাত্র {n}টি বাকি — তাড়াতাড়ি করুন!',
    inStock: 'স্টকে আছে',
    notifyMe: '🔔 পাওয়া গেলে জানান',
    youllBeNotified: '🔔 আপনাকে জানানো হবে',
    loginToNotify: 'জানতে লগইন করুন',
    notificationRemoved: 'বিজ্ঞপ্তি সরানো হয়েছে',
    somethingWentWrong: 'কিছু ভুল হয়েছে',
    whyYoullLoveIt: 'কেন আপনি এটি পছন্দ করবেন:',
    organicIngredients: '100% জৈব উপাদান',
    sustainablySourced: 'টেকসই উৎস',
    noPreservatives: 'কোনো কৃত্রিম প্রিজারভেটিভ নেই',
    ratingsReviews: 'রেটিং ও রিভিউ',
    review: 'রিভিউ',
    reviews: 'রিভিউ',
    writeReview: '✍️ রিভিউ লিখুন',
    editReview: '✏️ রিভিউ সম্পাদনা',
    yourRating: 'আপনার রেটিং:',
    reviewPlaceholder: 'এই পণ্যের সাথে আপনার অভিজ্ঞতা শেয়ার করুন... (ঐচ্ছিক)',
    submitReview: 'রিভিউ জমা দিন',
    updateReview: 'রিভিউ আপডেট করুন',
    submitting: 'জমা হচ্ছে...',
    signInToReview: 'এই পণ্যটি কেনার পর রিভিউ লিখতে সাইন ইন করুন।',
    purchaseToReview: 'রিভিউ দিতে এই পণ্যটি কিনুন।',
    noReviews: 'এখনো কোনো রিভিউ নেই। প্রথম রিভিউ লিখুন!',
    you: 'আপনি',
    loadingReviews: 'রিভিউ লোড হচ্ছে...',
    pleaseSelectRating: 'রেটিং নির্বাচন করুন',
    enableNotifPrompt: 'অর্ডার আপডেট এবং ব্যাক-ইন-স্টক অ্যালার্টের জন্য বিজ্ঞপ্তি সক্ষম করুন?',
    enable: 'সক্ষম',
    notNow: 'এখন না',
    notificationsEnabled: 'বিজ্ঞপ্তি সক্ষম!',
    myOrders: 'আমার অর্ডার',
    accountSettings: 'অ্যাকাউন্ট সেটিংস',
    profileInfo: 'প্রোফাইল তথ্য',
    manageAddresses: 'ঠিকানা পরিচালনা',
    notifications: 'বিজ্ঞপ্তি',
    payments: 'পেমেন্ট',
    giftCards: 'গিফট কার্ড',
    savedUpi: 'সেভড UPI',
    savedCards: 'সেভড কার্ড',
    hello: 'হ্যালো,',
    personalInfo: 'ব্যক্তিগত তথ্য',
    edit: 'সম্পাদনা',
    yourGender: 'আপনার লিঙ্গ',
    male: 'পুরুষ',
    female: 'মহিলা',
    mobileNumber: 'মোবাইল নম্বর',
    save: 'সেভ',
    savingUpper: 'সেভ হচ্ছে...',
    addNewAddress: 'নতুন ঠিকানা যোগ করুন',
    addressType: 'ঠিকানার ধরন',
    home: 'বাড়ি',
    work: 'অফিস',
    saveAndDeliver: 'সেভ করুন ও এখানে ডেলিভারি দিন',
    delete: 'মুছুন',
    locality: 'এলাকা',
    pushNotifications: 'পুশ বিজ্ঞপ্তি',
    stayUpdated: 'আপডেট থাকুন!',
    pushDescription: 'অর্ডার শিপিং আপডেট এবং আপনার পছন্দের আউট-অফ-স্টক পণ্য ফিরে এলে তাৎক্ষণিক অ্যালার্ট পান।',
    enableNotifications: 'বিজ্ঞপ্তি সক্ষম করুন',
    enableInBrowser: 'আপনার ব্রাউজার সেটিংসে বিজ্ঞপ্তি সক্ষম করুন।',
    noGiftCards: 'কোনো গিফট কার্ড নেই',
    noGiftCardsDesc: 'আপনি এখনো কোনো গিফট কার্ড যোগ করেননি।',
    addGiftCard: 'গিফট কার্ড যোগ করুন',
    noSavedUpi: 'কোনো সেভড UPI নেই',
    noSavedUpiDesc: 'দ্রুত পেমেন্টের জন্য আপনার UPI ID সেভ করুন।',
    noSavedCards: 'কোনো সেভড কার্ড নেই',
    noSavedCardsDesc: 'সহজ চেকআউটের জন্য আপনার ক্রেডিট/ডেবিট কার্ড সেভ করুন।',
    orderedOn: 'অর্ডার করা হয়েছে',
    noOrdersFound: 'কোনো অর্ডার পাওয়া যায়নি।',
    orderConfirmed: 'অর্ডার নিশ্চিত!',
    thankYou: 'Oatbites by SEJ থেকে কেনাকাটার জন্য ধন্যবাদ',
    orderId: 'অর্ডার আইডি',
    orderReceivedMsg: 'আমরা আপনার অর্ডার পেয়েছি এবং যত্ন সহকারে প্রস্তুত করছি। আপনি আপনার ড্যাশবোর্ড থেকে অর্ডারের স্থিতি ট্র্যাক করতে পারেন।',
    viewMyOrders: 'আমার অর্ডার দেখুন',
    continueShopping: 'কেনাকাটা চালিয়ে যান',
    loading: 'লোড হচ্ছে...',
    copyright: '© 2026 ওটবাইটস বাই SEJ। সর্বস্বত্ব সংরক্ষিত।',
    language: 'ভাষা',
  },
  ta: {
    aboutUs: 'எங்களைப் பற்றி',
    admin: 'நிர்வாகி',
    signIn: 'உள்நுழைய',
    dashboard: 'டாஷ்போர்டு',
    signOut: 'வெளியேறு',
    deliverTo: 'வழங்குமிடம்',
    setAddress: 'முகவரியைத் தேர்ந்தெடுக்கவும்',
    heroTitle: 'ஆரோக்கியமான &',
    heroTitle2: 'சுவையான.',
    heroSubtitle: 'மொறுமொறுப்பை அனுபவியுங்கள். அன்பு, அக்கறை மற்றும் சிறந்த இயற்கை பொருட்களால் தயாரிக்கப்பட்ட பிரீமியம் ஓட்பைட்ஸ்.',
    shopNow: 'இப்போது வாங்குங்கள்',
    featuredOatbites: 'சிறப்பு ஓட்பைட்ஸ்',
    viewAllProducts: 'அனைத்து தயாரிப்புகளையும் காண',
    addToCart: 'கார்ட்டில் சேர்',
    inCart: 'கார்ட்டில் உள்ளது',
    customer: 'வாடிக்கையாளர்',
    yourOrders: 'உங்கள் ஆர்டர்கள்',
    noOrders: 'நீங்கள் இன்னும் ஆர்டர் செய்யவில்லை.',
    startShopping: 'ஷாப்பிங் தொடங்குங்கள்',
    editProfile: 'சுயவிவரத்தை திருத்து',
    saveChanges: 'மாற்றங்களைச் சேமி',
    saving: 'சேமிக்கிறது...',
    profileUpdated: 'சுயவிவரம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது!',
    phone: 'தொலைபேசி எண்',
    address: 'முகவரி',
    name: 'முழு பெயர்',
    email: 'மின்னஞ்சல்',
    cancel: 'ரத்து செய்',
    products: 'தயாரிப்புகள்',
    searchProducts: 'தயாரிப்புகளைத் தேடுங்கள்...',
    allProducts: 'அனைத்து தயாரிப்புகள்',
    outOfStock: 'இருப்பில் இல்லை',
    checkout: 'செக்அவுட்',
    shippingDetails: 'ஷிப்பிங் விவரங்கள்',
    fullName: 'முழு பெயர்',
    streetAddress: 'தெரு முகவரி',
    city: 'நகரம்',
    state: 'மாநிலம்',
    pincode: 'பின்கோட்',
    orderSummary: 'ஆர்டர் சுருக்கம்',
    subtotal: 'துணைக்கூட்டு',
    shipping: 'ஷிப்பிங்',
    free: 'இலவசம்',
    total: 'மொத்தம்',
    payNow: 'இப்போது செலுத்துங்கள்',
    welcomeBack: 'மீண்டும் வரவேற்கிறோம்',
    signInSubtitle: 'உங்கள் ஓட்பைட்ஸ் கணக்கில் உள்நுழையவும்',
    emailAddress: 'மின்னஞ்சல் முகவரி',
    password: 'கடவுச்சொல்',
    signingIn: 'உள்நுழைகிறது...',
    or: 'அல்லது',
    continueWithGoogle: 'Google மூலம் தொடரவும்',
    signUpWithGoogle: 'Google மூலம் பதிவு செய்யவும்',
    noAccount: 'கணக்கு இல்லையா?',
    signUp: 'பதிவு செய்',
    createAccount: 'கணக்கு உருவாக்கு',
    createAccountSubtitle: 'ஷாப்பிங் தொடங்க ஓட்பைட்ஸில் சேரவும்',
    creatingAccount: 'கணக்கு உருவாக்கப்படுகிறது...',
    hasAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
    men: 'ஆண்',
    women: 'பெண்',
    backToProducts: '← தயாரிப்புகளுக்குத் திரும்பு',
    lowStock: 'மட்டும் {n} மீதமுள்ளது — விரைவில்!',
    inStock: 'இருப்பில் உள்ளது',
    notifyMe: '🔔 கிடைக்கும்போது தெரிவிக்கவும்',
    youllBeNotified: '🔔 உங்களுக்கு தெரிவிக்கப்படும்',
    loginToNotify: 'அறிவிப்புக்கு உள்நுழையவும்',
    notificationRemoved: 'அறிவிப்பு நீக்கப்பட்டது',
    somethingWentWrong: 'ஏதோ தவறு நடந்தது',
    whyYoullLoveIt: 'நீங்கள் ஏன் விரும்புவீர்கள்:',
    organicIngredients: '100% இயற்கை பொருட்கள்',
    sustainablySourced: 'நிலையான மூலம்',
    noPreservatives: 'செயற்கை பதப்படுத்திகள் இல்லை',
    ratingsReviews: 'மதிப்பீடுகள் & விமர்சனங்கள்',
    review: 'விமர்சனம்',
    reviews: 'விமர்சனங்கள்',
    writeReview: '✍️ விமர்சனம் எழுதுங்கள்',
    editReview: '✏️ விமர்சனம் திருத்து',
    yourRating: 'உங்கள் மதிப்பீடு:',
    reviewPlaceholder: 'இந்த தயாரிப்புடன் உங்கள் அனுபவத்தைப் பகிரவும்... (விருப்பம்)',
    submitReview: 'விமர்சனம் சமர்ப்பிக்கவும்',
    updateReview: 'விமர்சனம் புதுப்பிக்கவும்',
    submitting: 'சமர்ப்பிக்கிறது...',
    signInToReview: 'இந்த தயாரிப்பை வாங்கிய பிறகு விமர்சனம் எழுத உள்நுழையவும்.',
    purchaseToReview: 'விமர்சனம் எழுத இந்த தயாரிப்பை வாங்குங்கள்.',
    noReviews: 'இன்னும் விமர்சனங்கள் இல்லை. முதலில் விமர்சனம் எழுதுங்கள்!',
    you: 'நீங்கள்',
    loadingReviews: 'விமர்சனங்கள் ஏற்றப்படுகின்றன...',
    pleaseSelectRating: 'மதிப்பீட்டைத் தேர்ந்தெடுக்கவும்',
    enableNotifPrompt: 'ஆர்டர் புதுப்பிப்புகள் மற்றும் பேக்-இன்-ஸ்டாக் எச்சரிக்கைகளுக்கு அறிவிப்புகளை இயக்கவா?',
    enable: 'இயக்கு',
    notNow: 'இப்போது வேண்டாம்',
    notificationsEnabled: 'அறிவிப்புகள் இயக்கப்பட்டன!',
    myOrders: 'எனது ஆர்டர்கள்',
    accountSettings: 'கணக்கு அமைப்புகள்',
    profileInfo: 'சுயவிவர தகவல்',
    manageAddresses: 'முகவரிகளை நிர்வகிக்கவும்',
    notifications: 'அறிவிப்புகள்',
    payments: 'கட்டணங்கள்',
    giftCards: 'கிஃப்ட் கார்டுகள்',
    savedUpi: 'சேமித்த UPI',
    savedCards: 'சேமித்த கார்டுகள்',
    hello: 'வணக்கம்,',
    personalInfo: 'தனிப்பட்ட தகவல்',
    edit: 'திருத்து',
    yourGender: 'உங்கள் பாலினம்',
    male: 'ஆண்',
    female: 'பெண்',
    mobileNumber: 'மொபைல் எண்',
    save: 'சேமி',
    savingUpper: 'சேமிக்கிறது...',
    addNewAddress: 'புதிய முகவரி சேர்க்கவும்',
    addressType: 'முகவரி வகை',
    home: 'வீடு',
    work: 'அலுவலகம்',
    saveAndDeliver: 'சேமித்து இங்கே டெலிவரி செய்யுங்கள்',
    delete: 'நீக்கு',
    locality: 'பகுதி',
    pushNotifications: 'புஷ் அறிவிப்புகள்',
    stayUpdated: 'புதுப்பிக்கப்பட்ட நிலையில் இருங்கள்!',
    pushDescription: 'ஆர்டர் ஷிப்பிங் புதுப்பிப்புகள் மற்றும் உங்கள் விருப்ப அவுட்-ஆஃப்-ஸ்டாக் பொருட்கள் திரும்பி வரும்போது உடனடி எச்சரிக்கைகளைப் பெறுங்கள்.',
    enableNotifications: 'அறிவிப்புகளை இயக்கு',
    enableInBrowser: 'உங்கள் உலாவி அமைப்புகளில் அறிவிப்புகளை இயக்கவும்.',
    noGiftCards: 'கிஃப்ட் கார்டுகள் இல்லை',
    noGiftCardsDesc: 'நீங்கள் இன்னும் கிஃப்ட் கார்டுகள் சேர்க்கவில்லை.',
    addGiftCard: 'கிஃப்ட் கார்ட் சேர்க்கவும்',
    noSavedUpi: 'சேமித்த UPI இல்லை',
    noSavedUpiDesc: 'விரைவான கட்டணங்களுக்கு உங்கள் UPI ID-ஐ சேமியுங்கள்.',
    noSavedCards: 'சேமித்த கார்டுகள் இல்லை',
    noSavedCardsDesc: 'எளிதான செக்அவுட்டிற்கு உங்கள் கிரெடிட்/டெபிட் கார்டுகளை சேமியுங்கள்.',
    orderedOn: 'ஆர்டர் செய்யப்பட்டது',
    noOrdersFound: 'ஆர்டர்கள் எதுவும் இல்லை.',
    orderConfirmed: 'ஆர்டர் உறுதிசெய்யப்பட்டது!',
    thankYou: 'Oatbites by SEJ-இல் ஷாப்பிங் செய்ததற்கு நன்றி',
    orderId: 'ஆர்டர் ஐடி',
    orderReceivedMsg: 'உங்கள் ஆர்டரைப் பெற்றுள்ளோம், அக்கறையுடன் தயாரிக்கிறோம். உங்கள் டாஷ்போர்டில் ஆர்டர் நிலையைக் கண்காணிக்கலாம்.',
    viewMyOrders: 'எனது ஆர்டர்களைக் காண',
    continueShopping: 'ஷாப்பிங் தொடரவும்',
    loading: 'ஏற்றுகிறது...',
    copyright: '© 2026 ஓட்பைட்ஸ் பை SEJ. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
    language: 'மொழி',
  },
  te: {
    aboutUs: 'మా గురించి',
    admin: 'అడ్మిన్',
    signIn: 'సైన్ ఇన్',
    dashboard: 'డాష్‌బోర్డ్',
    signOut: 'సైన్ అవుట్',
    deliverTo: 'ఇక్కడకు బట్వాడా చేయండి',
    setAddress: 'మీ చిరునామాను ఎంచుకోండి',
    heroTitle: 'ఆరోగ్యకరమైన &',
    heroTitle2: 'రుచికరమైన.',
    heroSubtitle: 'క్రంచ్ అనుభవించండి. ప్రేమ, శ్రద్ధ మరియు ఉత్తమ సేంద్రీయ పదార్థాలతో తయారు చేసిన ప్రీమియం ఓట్‌బైట్స్.',
    shopNow: 'ఇప్పుడు కొనండి',
    featuredOatbites: 'ప్రత్యేక ఓట్‌బైట్స్',
    viewAllProducts: 'అన్ని ఉత్పత్తులు చూడండి',
    addToCart: 'కార్ట్‌కు జోడించండి',
    inCart: 'కార్ట్‌లో ఉంది',
    customer: 'కస్టమర్',
    yourOrders: 'మీ ఆర్డర్లు',
    noOrders: 'మీరు ఇంకా ఆర్డర్ చేయలేదు.',
    startShopping: 'షాపింగ్ ప్రారంభించండి',
    editProfile: 'ప్రొఫైల్ సవరించు',
    saveChanges: 'మార్పులు సేవ్ చేయి',
    saving: 'సేవ్ చేస్తోంది...',
    profileUpdated: 'ప్రొఫైల్ విజయవంతంగా అప్‌డేట్ అయింది!',
    phone: 'ఫోన్ నంబర్',
    address: 'చిరునామా',
    name: 'పూర్తి పేరు',
    email: 'ఇమెయిల్',
    cancel: 'రద్దు చేయి',
    products: 'ఉత్పత్తులు',
    searchProducts: 'ఉత్పత్తులు వెతకండి...',
    allProducts: 'అన్ని ఉత్పత్తులు',
    outOfStock: 'స్టాక్‌లో లేదు',
    checkout: 'చెక్‌అవుట్',
    shippingDetails: 'షిప్పింగ్ వివరాలు',
    fullName: 'పూర్తి పేరు',
    streetAddress: 'వీధి చిరునామా',
    city: 'నగరం',
    state: 'రాష్ట్రం',
    pincode: 'పిన్‌కోడ్',
    orderSummary: 'ఆర్డర్ సారాంశం',
    subtotal: 'ఉపమొత్తం',
    shipping: 'షిప్పింగ్',
    free: 'ఉచితం',
    total: 'మొత్తం',
    payNow: 'ఇప్పుడు చెల్లించండి',
    welcomeBack: 'తిరిగి స్వాగతం',
    signInSubtitle: 'మీ ఓట్‌బైట్స్ ఖాతాలో సైన్ ఇన్ చేయండి',
    emailAddress: 'ఇమెయిల్ చిరునామా',
    password: 'పాస్‌వర్డ్',
    signingIn: 'సైన్ ఇన్ అవుతోంది...',
    or: 'లేదా',
    continueWithGoogle: 'Google తో కొనసాగించండి',
    signUpWithGoogle: 'Google తో సైన్ అప్',
    noAccount: 'ఖాతా లేదా?',
    signUp: 'సైన్ అప్',
    createAccount: 'ఖాతా సృష్టించండి',
    createAccountSubtitle: 'షాపింగ్ ప్రారంభించడానికి ఓట్‌బైట్స్‌లో చేరండి',
    creatingAccount: 'ఖాతా సృష్టించబడుతోంది...',
    hasAccount: 'ఇప్పటికే ఖాతా ఉందా?',
    men: 'పురుషులు',
    women: 'మహిళలు',
    backToProducts: '← ఉత్పత్తులకు తిరిగి వెళ్ళు',
    lowStock: 'కేవలం {n} మిగిలి ఉన్నాయి — త్వరపడండి!',
    inStock: 'స్టాక్‌లో ఉంది',
    notifyMe: '🔔 అందుబాటులో ఉన్నప్పుడు తెలియజేయండి',
    youllBeNotified: '🔔 మీకు తెలియజేయబడుతుంది',
    loginToNotify: 'తెలియజేయడానికి లాగిన్ చేయండి',
    notificationRemoved: 'నోటిఫికేషన్ తొలగించబడింది',
    somethingWentWrong: 'ఏదో తప్పు జరిగింది',
    whyYoullLoveIt: 'మీరు ఎందుకు ఇష్టపడతారు:',
    organicIngredients: '100% సేంద్రీయ పదార్థాలు',
    sustainablySourced: 'స్థిరమైన మూలం',
    noPreservatives: 'కృత్రిమ ప్రిజర్వేటివ్‌లు లేవు',
    ratingsReviews: 'రేటింగ్‌లు & రివ్యూలు',
    review: 'రివ్యూ',
    reviews: 'రివ్యూలు',
    writeReview: '✍️ రివ్యూ రాయండి',
    editReview: '✏️ రివ్యూ సవరించు',
    yourRating: 'మీ రేటింగ్:',
    reviewPlaceholder: 'ఈ ఉత్పత్తితో మీ అనుభవాన్ని పంచుకోండి... (ఐచ్ఛికం)',
    submitReview: 'రివ్యూ సమర్పించండి',
    updateReview: 'రివ్యూ అప్‌డేట్ చేయండి',
    submitting: 'సమర్పిస్తోంది...',
    signInToReview: 'ఈ ఉత్పత్తిని కొనుగోలు చేసిన తర్వాత రివ్యూ రాయడానికి సైన్ ఇన్ చేయండి.',
    purchaseToReview: 'రివ్యూ రాయడానికి ఈ ఉత్పత్తిని కొనుగోలు చేయండి.',
    noReviews: 'ఇంకా రివ్యూలు లేవు. మొదటి రివ్యూ రాయండి!',
    you: 'మీరు',
    loadingReviews: 'రివ్యూలు లోడ్ అవుతున్నాయి...',
    pleaseSelectRating: 'రేటింగ్ ఎంచుకోండి',
    enableNotifPrompt: 'ఆర్డర్ అప్‌డేట్‌లు మరియు బ్యాక్-ఇన్-స్టాక్ అలర్ట్‌ల కోసం నోటిఫికేషన్‌లను ఎనేబుల్ చేయాలా?',
    enable: 'ఎనేబుల్',
    notNow: 'ఇప్పుడు కాదు',
    notificationsEnabled: 'నోటిఫికేషన్‌లు ఎనేబుల్!',
    myOrders: 'నా ఆర్డర్లు',
    accountSettings: 'ఖాతా సెట్టింగ్‌లు',
    profileInfo: 'ప్రొఫైల్ సమాచారం',
    manageAddresses: 'చిరునామాలు నిర్వహించండి',
    notifications: 'నోటిఫికేషన్‌లు',
    payments: 'చెల్లింపులు',
    giftCards: 'గిఫ్ట్ కార్డ్‌లు',
    savedUpi: 'సేవ్ చేసిన UPI',
    savedCards: 'సేవ్ చేసిన కార్డ్‌లు',
    hello: 'హలో,',
    personalInfo: 'వ్యక్తిగత సమాచారం',
    edit: 'సవరించు',
    yourGender: 'మీ లింగం',
    male: 'పురుషుడు',
    female: 'స్త్రీ',
    mobileNumber: 'మొబైల్ నంబర్',
    save: 'సేవ్',
    savingUpper: 'సేవ్ చేస్తోంది...',
    addNewAddress: 'కొత్త చిరునామా జోడించండి',
    addressType: 'చిరునామా రకం',
    home: 'ఇల్లు',
    work: 'ఆఫీసు',
    saveAndDeliver: 'సేవ్ చేసి ఇక్కడ డెలివరీ చేయండి',
    delete: 'తొలగించు',
    locality: 'ప్రాంతం',
    pushNotifications: 'పుష్ నోటిఫికేషన్‌లు',
    stayUpdated: 'అప్‌డేట్‌గా ఉండండి!',
    pushDescription: 'ఆర్డర్ షిప్పింగ్ అప్‌డేట్‌లు మరియు మీ ఇష్టమైన అవుట్-ఆఫ్-స్టాక్ ఐటమ్‌లు తిరిగి వచ్చినప్పుడు తక్షణ అలర్ట్‌లు పొందండి.',
    enableNotifications: 'నోటిఫికేషన్‌లు ఎనేబుల్ చేయండి',
    enableInBrowser: 'మీ బ్రౌజర్ సెట్టింగ్‌లలో నోటిఫికేషన్‌లను ఎనేబుల్ చేయండి.',
    noGiftCards: 'గిఫ్ట్ కార్డ్‌లు లేవు',
    noGiftCardsDesc: 'మీరు ఇంకా గిఫ్ట్ కార్డ్‌లు జోడించలేదు.',
    addGiftCard: 'గిఫ్ట్ కార్డ్ జోడించండి',
    noSavedUpi: 'సేవ్ చేసిన UPI లేదు',
    noSavedUpiDesc: 'వేగవంతమైన చెల్లింపుల కోసం మీ UPI ID సేవ్ చేయండి.',
    noSavedCards: 'సేవ్ చేసిన కార్డ్‌లు లేవు',
    noSavedCardsDesc: 'సులభ చెక్‌అవుట్ కోసం మీ క్రెడిట్/డెబిట్ కార్డ్‌లను సేవ్ చేయండి.',
    orderedOn: 'ఆర్డర్ చేయబడింది',
    noOrdersFound: 'ఆర్డర్లు కనుగొనబడలేదు.',
    orderConfirmed: 'ఆర్డర్ నిర్ధారించబడింది!',
    thankYou: 'Oatbites by SEJ లో షాపింగ్ చేసినందుకు ధన్యవాదాలు',
    orderId: 'ఆర్డర్ ఐడి',
    orderReceivedMsg: 'మేము మీ ఆర్డర్‌ను స్వీకరించాము మరియు శ్రద్ధతో సిద్ధం చేస్తున్నాము. మీ డాష్‌బోర్డ్ నుండి ఆర్డర్ స్థితిని ట్రాక్ చేయవచ్చు.',
    viewMyOrders: 'నా ఆర్డర్లు చూడండి',
    continueShopping: 'షాపింగ్ కొనసాగించండి',
    loading: 'లోడ్ అవుతోంది...',
    copyright: '© 2026 ఓట్‌బైట్స్ బై SEJ. అన్ని హక్కులు రిజర్వ్ చేయబడ్డాయి.',
    language: 'భాష',
  },
  mr: {
    aboutUs: 'आमच्याबद्दल',
    admin: 'अॅडमिन',
    signIn: 'साइन इन',
    dashboard: 'डॅशबोर्ड',
    signOut: 'साइन आउट',
    deliverTo: 'येथे डिलिव्हर करा',
    setAddress: 'तुमचा पत्ता निवडा',
    heroTitle: 'आरोग्यदायी आणि',
    heroTitle2: 'चविष्ट.',
    heroSubtitle: 'क्रंचचा अनुभव घ्या. प्रेम, काळजी आणि उत्कृष्ट सेंद्रिय घटकांनी बनवलेले प्रीमियम ओटबाइट्स.',
    shopNow: 'आता खरेदी करा',
    featuredOatbites: 'विशेष ओटबाइट्स',
    viewAllProducts: 'सर्व उत्पादने पहा',
    addToCart: 'कार्टमध्ये जोडा',
    inCart: 'कार्टमध्ये',
    customer: 'ग्राहक',
    yourOrders: 'तुमचे ऑर्डर',
    noOrders: 'तुम्ही अजून कोणतीही ऑर्डर दिलेली नाही.',
    startShopping: 'खरेदी सुरू करा',
    editProfile: 'प्रोफाइल संपादित करा',
    saveChanges: 'बदल जतन करा',
    saving: 'जतन करत आहे...',
    profileUpdated: 'प्रोफाइल यशस्वीरित्या अपडेट झाले!',
    phone: 'फोन नंबर',
    address: 'पत्ता',
    name: 'पूर्ण नाव',
    email: 'ईमेल',
    cancel: 'रद्द करा',
    products: 'उत्पादने',
    searchProducts: 'उत्पादने शोधा...',
    allProducts: 'सर्व उत्पादने',
    outOfStock: 'स्टॉकमध्ये नाही',
    checkout: 'चेकआउट',
    shippingDetails: 'शिपिंग तपशील',
    fullName: 'पूर्ण नाव',
    streetAddress: 'रस्त्याचा पत्ता',
    city: 'शहर',
    state: 'राज्य',
    pincode: 'पिनकोड',
    orderSummary: 'ऑर्डर सारांश',
    subtotal: 'उपएकूण',
    shipping: 'शिपिंग',
    free: 'मोफत',
    total: 'एकूण',
    payNow: 'आता पेमेंट करा',
    welcomeBack: 'पुन्हा स्वागत',
    signInSubtitle: 'तुमच्या ओटबाइट्स खात्यात साइन इन करा',
    emailAddress: 'ईमेल पत्ता',
    password: 'पासवर्ड',
    signingIn: 'साइन इन होत आहे...',
    or: 'किंवा',
    continueWithGoogle: 'Google सह सुरू ठेवा',
    signUpWithGoogle: 'Google सह साइन अप',
    noAccount: 'खाते नाही?',
    signUp: 'साइन अप',
    createAccount: 'खाते तयार करा',
    createAccountSubtitle: 'खरेदी सुरू करण्यासाठी ओटबाइट्स जॉइन करा',
    creatingAccount: 'खाते तयार होत आहे...',
    hasAccount: 'आधीच खाते आहे?',
    men: 'पुरुष',
    women: 'महिला',
    backToProducts: '← उत्पादनांकडे परत',
    lowStock: 'फक्त {n} शिल्लक — घाई करा!',
    inStock: 'स्टॉकमध्ये',
    notifyMe: '🔔 उपलब्ध झाल्यावर कळवा',
    youllBeNotified: '🔔 तुम्हाला कळवले जाईल',
    loginToNotify: 'सूचनेसाठी लॉगिन करा',
    notificationRemoved: 'सूचना काढली',
    somethingWentWrong: 'काहीतरी चूक झाली',
    whyYoullLoveIt: 'तुम्हाला का आवडेल:',
    organicIngredients: '100% सेंद्रिय घटक',
    sustainablySourced: 'शाश्वत स्रोत',
    noPreservatives: 'कोणतेही कृत्रिम संरक्षक नाहीत',
    ratingsReviews: 'रेटिंग आणि पुनरावलोकने',
    review: 'पुनरावलोकन',
    reviews: 'पुनरावलोकने',
    writeReview: '✍️ पुनरावलोकन लिहा',
    editReview: '✏️ पुनरावलोकन संपादित करा',
    yourRating: 'तुमची रेटिंग:',
    reviewPlaceholder: 'या उत्पादनासह तुमचा अनुभव शेअर करा... (वैकल्पिक)',
    submitReview: 'पुनरावलोकन सबमिट करा',
    updateReview: 'पुनरावलोकन अपडेट करा',
    submitting: 'सबमिट होत आहे...',
    signInToReview: 'हे उत्पादन खरेदी केल्यानंतर पुनरावलोकन लिहिण्यासाठी साइन इन करा.',
    purchaseToReview: 'पुनरावलोकन लिहिण्यासाठी हे उत्पादन खरेदी करा.',
    noReviews: 'अजून पुनरावलोकने नाहीत. पहिले पुनरावलोकन लिहा!',
    you: 'तुम्ही',
    loadingReviews: 'पुनरावलोकने लोड होत आहेत...',
    pleaseSelectRating: 'कृपया रेटिंग निवडा',
    enableNotifPrompt: 'ऑर्डर अपडेट आणि बॅक-इन-स्टॉक अलर्टसाठी सूचना सक्षम करायच्या?',
    enable: 'सक्षम करा',
    notNow: 'आता नको',
    notificationsEnabled: 'सूचना सक्षम!',
    myOrders: 'माझे ऑर्डर',
    accountSettings: 'खाते सेटिंग्ज',
    profileInfo: 'प्रोफाइल माहिती',
    manageAddresses: 'पत्ते व्यवस्थापित करा',
    notifications: 'सूचना',
    payments: 'पेमेंट',
    giftCards: 'गिफ्ट कार्ड',
    savedUpi: 'सेव्ह केलेले UPI',
    savedCards: 'सेव्ह केलेले कार्ड',
    hello: 'नमस्कार,',
    personalInfo: 'वैयक्तिक माहिती',
    edit: 'संपादित करा',
    yourGender: 'तुमचे लिंग',
    male: 'पुरुष',
    female: 'महिला',
    mobileNumber: 'मोबाइल नंबर',
    save: 'सेव्ह करा',
    savingUpper: 'सेव्ह होत आहे...',
    addNewAddress: 'नवीन पत्ता जोडा',
    addressType: 'पत्त्याचा प्रकार',
    home: 'घर',
    work: 'कार्यालय',
    saveAndDeliver: 'सेव्ह करा आणि येथे डिलिव्हर करा',
    delete: 'हटवा',
    locality: 'परिसर',
    pushNotifications: 'पुश सूचना',
    stayUpdated: 'अपडेट राहा!',
    pushDescription: 'ऑर्डर शिपिंग अपडेट आणि तुमच्या आवडत्या आउट-ऑफ-स्टॉक वस्तू परत आल्यावर तात्काळ अलर्ट मिळवा.',
    enableNotifications: 'सूचना सक्षम करा',
    enableInBrowser: 'कृपया तुमच्या ब्राउझर सेटिंग्जमध्ये सूचना सक्षम करा.',
    noGiftCards: 'गिफ्ट कार्ड नाहीत',
    noGiftCardsDesc: 'तुम्ही अजून गिफ्ट कार्ड जोडलेले नाहीत.',
    addGiftCard: 'गिफ्ट कार्ड जोडा',
    noSavedUpi: 'सेव्ह केलेले UPI नाही',
    noSavedUpiDesc: 'जलद पेमेंटसाठी तुमची UPI ID सेव्ह करा.',
    noSavedCards: 'सेव्ह केलेले कार्ड नाहीत',
    noSavedCardsDesc: 'सहज चेकआउटसाठी तुमचे क्रेडिट/डेबिट कार्ड सेव्ह करा.',
    orderedOn: 'ऑर्डर केले',
    noOrdersFound: 'ऑर्डर सापडले नाहीत.',
    orderConfirmed: 'ऑर्डर पुष्टी!',
    thankYou: 'Oatbites by SEJ मधून खरेदी केल्याबद्दल धन्यवाद',
    orderId: 'ऑर्डर आयडी',
    orderReceivedMsg: 'आम्हाला तुमचा ऑर्डर मिळाला आहे आणि काळजीपूर्वक तयार करत आहोत. तुम्ही तुमच्या डॅशबोर्डवरून ऑर्डर स्थिती ट्रॅक करू शकता.',
    viewMyOrders: 'माझे ऑर्डर पहा',
    continueShopping: 'खरेदी सुरू ठेवा',
    loading: 'लोड होत आहे...',
    copyright: '© 2026 ओटबाइट्स बाय SEJ. सर्व हक्क राखीव.',
    language: 'भाषा',
  },
};

const LANGUAGE_NAMES = {
  en: 'English',
  hi: 'हिन्दी',
  bn: 'বাংলা',
  ta: 'தமிழ்',
  te: 'తెలుగు',
  mr: 'मराठी',
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [locale, setLocale] = useState('en');

  useEffect(() => {
    const saved = localStorage.getItem('ob_lang');
    if (saved && translations[saved]) {
      setLocale(saved);
    }
  }, []);

  const changeLanguage = (lang) => {
    setLocale(lang);
    localStorage.setItem('ob_lang', lang);
  };

  const t = (key) => {
    return translations[locale]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ locale, changeLanguage, t, LANGUAGE_NAMES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
