'use client';

import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    // Header
    aboutUs: 'About Us',
    admin: 'Admin',
    signIn: 'Sign In',
    dashboard: 'Dashboard',
    signOut: 'Sign Out',
    // Home
    heroTitle: 'Healthy &',
    heroTitle2: 'Delicious.',
    heroSubtitle: 'Experience the crunch. Premium oatbites crafted with love, care, and the finest organic ingredients.',
    shopNow: 'Shop Now',
    featuredOatbites: 'Featured Oatbites',
    viewAllProducts: 'View All Products',
    addToCart: 'Add to Cart',
    inCart: 'In Cart',
    // Dashboard
    customer: 'Customer',
    yourOrders: 'Your Orders',
    noOrders: "You haven't placed any orders yet.",
    startShopping: 'Start Shopping',
    editProfile: 'Edit Profile',
    saveChanges: 'Save Changes',
    saving: 'Saving...',
    profileUpdated: 'Profile updated successfully!',
    phone: 'Phone Number',
    address: 'Address',
    name: 'Full Name',
    email: 'Email',
    cancel: 'Cancel',
    // Products
    products: 'Products',
    searchProducts: 'Search products...',
    allProducts: 'All Products',
    outOfStock: 'Out of Stock',
    // Checkout
    checkout: 'Checkout',
    shippingDetails: 'Shipping Details',
    fullName: 'Full Name',
    streetAddress: 'Street Address',
    city: 'City',
    state: 'State',
    pincode: 'Pincode',
    orderSummary: 'Order Summary',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    free: 'Free',
    total: 'Total',
    payNow: 'Pay Now',
    // Auth
    welcomeBack: 'Welcome Back',
    signInSubtitle: 'Sign in to your Oatbites account',
    emailAddress: 'Email Address',
    password: 'Password',
    signingIn: 'Signing in...',
    or: 'OR',
    continueWithGoogle: 'Continue with Google',
    signUpWithGoogle: 'Sign up with Google',
    noAccount: "Don't have an account?",
    signUp: 'Sign Up',
    createAccount: 'Create Account',
    createAccountSubtitle: 'Join Oatbites to start shopping',
    creatingAccount: 'Creating account...',
    hasAccount: 'Already have an account?',
    men: 'Men',
    women: 'Women',
    // Footer
    copyright: '© 2026 Oatbites by SEJ. All rights reserved.',
    // Language
    language: 'Language',
  },
  hi: {
    aboutUs: 'हमारे बारे में',
    admin: 'एडमिन',
    signIn: 'साइन इन',
    dashboard: 'डैशबोर्ड',
    signOut: 'साइन आउट',
    heroTitle: 'स्वस्थ और',
    heroTitle2: 'स्वादिष्ट।',
    heroSubtitle: 'क्रंच का अनुभव करें। प्यार, देखभाल और बेहतरीन जैविक सामग्री से बने प्रीमियम ओटबाइट्स।',
    shopNow: 'अभी खरीदें',
    featuredOatbites: 'विशेष ओटबाइट्स',
    viewAllProducts: 'सभी उत्पाद देखें',
    addToCart: 'कार्ट में डालें',
    inCart: 'कार्ट में',
    customer: 'ग्राहक',
    yourOrders: 'आपके ऑर्डर',
    noOrders: 'आपने अभी तक कोई ऑर्डर नहीं दिया है।',
    startShopping: 'खरीदारी शुरू करें',
    editProfile: 'प्रोफ़ाइल संपादित करें',
    saveChanges: 'बदलाव सहेजें',
    saving: 'सहेज रहे हैं...',
    profileUpdated: 'प्रोफ़ाइल सफलतापूर्वक अपडेट हुई!',
    phone: 'फ़ोन नंबर',
    address: 'पता',
    name: 'पूरा नाम',
    email: 'ईमेल',
    cancel: 'रद्द करें',
    products: 'उत्पाद',
    searchProducts: 'उत्पाद खोजें...',
    allProducts: 'सभी उत्पाद',
    outOfStock: 'स्टॉक में नहीं',
    checkout: 'चेकआउट',
    shippingDetails: 'शिपिंग विवरण',
    fullName: 'पूरा नाम',
    streetAddress: 'सड़क का पता',
    city: 'शहर',
    state: 'राज्य',
    pincode: 'पिनकोड',
    orderSummary: 'ऑर्डर सारांश',
    subtotal: 'उपकुल',
    shipping: 'शिपिंग',
    free: 'मुफ़्त',
    total: 'कुल',
    payNow: 'अभी भुगतान करें',
    welcomeBack: 'फिर से स्वागत है',
    signInSubtitle: 'अपने ओटबाइट्स खाते में साइन इन करें',
    emailAddress: 'ईमेल पता',
    password: 'पासवर्ड',
    signingIn: 'साइन इन हो रहा है...',
    or: 'या',
    continueWithGoogle: 'Google से जारी रखें',
    signUpWithGoogle: 'Google से साइन अप',
    noAccount: 'खाता नहीं है?',
    signUp: 'साइन अप',
    createAccount: 'खाता बनाएं',
    createAccountSubtitle: 'खरीदारी शुरू करने के लिए ओटबाइट्स जॉइन करें',
    creatingAccount: 'खाता बनाया जा रहा है...',
    hasAccount: 'पहले से खाता है?',
    men: 'पुरुष',
    women: 'महिला',
    copyright: '© 2026 ओटबाइट्स बाय SEJ। सर्वाधिकार सुरक्षित।',
    language: 'भाषा',
  },
  bn: {
    aboutUs: 'আমাদের সম্পর্কে',
    admin: 'অ্যাডমিন',
    signIn: 'সাইন ইন',
    dashboard: 'ড্যাশবোর্ড',
    signOut: 'সাইন আউট',
    heroTitle: 'স্বাস্থ্যকর ও',
    heroTitle2: 'সুস্বাদু।',
    heroSubtitle: 'ক্রাঞ্চের অভিজ্ঞতা নিন। ভালোবাসা, যত্ন এবং সেরা জৈব উপাদান দিয়ে তৈরি প্রিমিয়াম ওটবাইটস।',
    shopNow: 'এখনই কিনুন',
    featuredOatbites: 'বিশেষ ওটবাইটস',
    viewAllProducts: 'সব পণ্য দেখুন',
    addToCart: 'কার্টে যোগ করুন',
    inCart: 'কার্টে আছে',
    customer: 'গ্রাহক',
    yourOrders: 'আপনার অর্ডার',
    noOrders: 'আপনি এখনও কোনো অর্ডার দেননি।',
    startShopping: 'কেনাকাটা শুরু করুন',
    editProfile: 'প্রোফাইল সম্পাদনা',
    saveChanges: 'পরিবর্তন সংরক্ষণ',
    saving: 'সংরক্ষণ হচ্ছে...',
    profileUpdated: 'প্রোফাইল সফলভাবে আপডেট হয়েছে!',
    phone: 'ফোন নম্বর',
    address: 'ঠিকানা',
    name: 'পুরো নাম',
    email: 'ইমেইল',
    cancel: 'বাতিল',
    products: 'পণ্য',
    searchProducts: 'পণ্য খুঁজুন...',
    allProducts: 'সব পণ্য',
    outOfStock: 'স্টকে নেই',
    checkout: 'চেকআউট',
    shippingDetails: 'শিপিং বিবরণ',
    fullName: 'পুরো নাম',
    streetAddress: 'রাস্তার ঠিকানা',
    city: 'শহর',
    state: 'রাজ্য',
    pincode: 'পিনকোড',
    orderSummary: 'অর্ডার সারাংশ',
    subtotal: 'উপমোট',
    shipping: 'শিপিং',
    free: 'বিনামূল্যে',
    total: 'মোট',
    payNow: 'এখনই পেমেন্ট করুন',
    welcomeBack: 'ফিরে আসুন',
    signInSubtitle: 'আপনার ওটবাইটস অ্যাকাউন্টে সাইন ইন করুন',
    emailAddress: 'ইমেইল ঠিকানা',
    password: 'পাসওয়ার্ড',
    signingIn: 'সাইন ইন হচ্ছে...',
    or: 'অথবা',
    continueWithGoogle: 'Google দিয়ে চালিয়ে যান',
    signUpWithGoogle: 'Google দিয়ে সাইন আপ',
    noAccount: 'অ্যাকাউন্ট নেই?',
    signUp: 'সাইন আপ',
    createAccount: 'অ্যাকাউন্ট তৈরি করুন',
    createAccountSubtitle: 'কেনাকাটা শুরু করতে ওটবাইটস যোগ দিন',
    creatingAccount: 'অ্যাকাউন্ট তৈরি হচ্ছে...',
    hasAccount: 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
    men: 'পুরুষ',
    women: 'মহিলা',
    copyright: '© 2026 ওটবাইটস বাই SEJ। সর্বস্বত্ব সংরক্ষিত।',
    language: 'ভাষা',
  },
  ta: {
    aboutUs: 'எங்களைப் பற்றி',
    admin: 'நிர்வாகி',
    signIn: 'உள்நுழைய',
    dashboard: 'டாஷ்போர்டு',
    signOut: 'வெளியேறு',
    heroTitle: 'ஆரோக்கியமான &',
    heroTitle2: 'சுவையான.',
    heroSubtitle: 'மொறுமொறுப்பை அனுபவியுங்கள். அன்பு, அக்கறை மற்றும் சிறந்த இயற்கை பொருட்களால் தயாரிக்கப்பட்ட பிரீமியம் ஓட்பைட்ஸ்.',
    shopNow: 'இப்போது வாங்குங்கள்',
    featuredOatbites: 'சிறப்பு ஓட்பைட்ஸ்',
    viewAllProducts: 'அனைத்து தயாரிப்புகளையும் காண',
    addToCart: 'கார்ட்டில் சேர்',
    inCart: 'கார்ட்டில் உள்ளது',
    customer: 'வாடிக்கையாளர்',
    yourOrders: 'உங்கள் ஆர்டர்கள்',
    noOrders: 'நீங்கள் இன்னும் ஆர்டர் செய்யவில்லை.',
    startShopping: 'ஷாப்பிங் தொடங்குங்கள்',
    editProfile: 'சுயவிவரத்தை திருத்து',
    saveChanges: 'மாற்றங்களைச் சேமி',
    saving: 'சேமிக்கிறது...',
    profileUpdated: 'சுயவிவரம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது!',
    phone: 'தொலைபேசி எண்',
    address: 'முகவரி',
    name: 'முழு பெயர்',
    email: 'மின்னஞ்சல்',
    cancel: 'ரத்து செய்',
    products: 'தயாரிப்புகள்',
    searchProducts: 'தயாரிப்புகளைத் தேடுங்கள்...',
    allProducts: 'அனைத்து தயாரிப்புகள்',
    outOfStock: 'இருப்பில் இல்லை',
    checkout: 'செக்அவுட்',
    shippingDetails: 'ஷிப்பிங் விவரங்கள்',
    fullName: 'முழு பெயர்',
    streetAddress: 'தெரு முகவரி',
    city: 'நகரம்',
    state: 'மாநிலம்',
    pincode: 'பின்கோட்',
    orderSummary: 'ஆர்டர் சுருக்கம்',
    subtotal: 'துணைக்கூட்டு',
    shipping: 'ஷிப்பிங்',
    free: 'இலவசம்',
    total: 'மொத்தம்',
    payNow: 'இப்போது செலுத்துங்கள்',
    welcomeBack: 'மீண்டும் வரவேற்கிறோம்',
    signInSubtitle: 'உங்கள் ஓட்பைட்ஸ் கணக்கில் உள்நுழையவும்',
    emailAddress: 'மின்னஞ்சல் முகவரி',
    password: 'கடவுச்சொல்',
    signingIn: 'உள்நுழைகிறது...',
    or: 'அல்லது',
    continueWithGoogle: 'Google மூலம் தொடரவும்',
    signUpWithGoogle: 'Google மூலம் பதிவு செய்யவும்',
    noAccount: 'கணக்கு இல்லையா?',
    signUp: 'பதிவு செய்',
    createAccount: 'கணக்கு உருவாக்கு',
    createAccountSubtitle: 'ஷாப்பிங் தொடங்க ஓட்பைட்ஸில் சேரவும்',
    creatingAccount: 'கணக்கு உருவாக்கப்படுகிறது...',
    hasAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
    men: 'ஆண்',
    women: 'பெண்',
    copyright: '© 2026 ஓட்பைட்ஸ் பை SEJ. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
    language: 'மொழி',
  },
  te: {
    aboutUs: 'మా గురించి',
    admin: 'అడ్మిన్',
    signIn: 'సైన్ ఇన్',
    dashboard: 'డాష్‌బోర్డ్',
    signOut: 'సైన్ అవుట్',
    heroTitle: 'ఆరోగ్యకరమైన &',
    heroTitle2: 'రుచికరమైన.',
    heroSubtitle: 'క్రంచ్ అనుభవించండి. ప్రేమ, శ్రద్ధ మరియు ఉత్తమ సేంద్రీయ పదార్థాలతో తయారు చేసిన ప్రీమియం ఓట్‌బైట్స్.',
    shopNow: 'ఇప్పుడు కొనండి',
    featuredOatbites: 'ప్రత్యేక ఓట్‌బైట్స్',
    viewAllProducts: 'అన్ని ఉత్పత్తులు చూడండి',
    addToCart: 'కార్ట్‌కు జోడించండి',
    inCart: 'కార్ట్‌లో ఉంది',
    customer: 'కస్టమర్',
    yourOrders: 'మీ ఆర్డర్లు',
    noOrders: 'మీరు ఇంకా ఆర్డర్ చేయలేదు.',
    startShopping: 'షాపింగ్ ప్రారంభించండి',
    editProfile: 'ప్రొఫైల్ సవరించు',
    saveChanges: 'మార్పులు సేవ్ చేయి',
    saving: 'సేవ్ చేస్తోంది...',
    profileUpdated: 'ప్రొఫైల్ విజయవంతంగా అప్‌డేట్ అయింది!',
    phone: 'ఫోన్ నంబర్',
    address: 'చిరునామా',
    name: 'పూర్తి పేరు',
    email: 'ఇమెయిల్',
    cancel: 'రద్దు చేయి',
    products: 'ఉత్పత్తులు',
    searchProducts: 'ఉత్పత్తులు వెతకండి...',
    allProducts: 'అన్ని ఉత్పత్తులు',
    outOfStock: 'స్టాక్‌లో లేదు',
    checkout: 'చెక్‌అవుట్',
    shippingDetails: 'షిప్పింగ్ వివరాలు',
    fullName: 'పూర్తి పేరు',
    streetAddress: 'వీధి చిరునామా',
    city: 'నగరం',
    state: 'రాష్ట్రం',
    pincode: 'పిన్‌కోడ్',
    orderSummary: 'ఆర్డర్ సారాంశం',
    subtotal: 'ఉపమొత్తం',
    shipping: 'షిప్పింగ్',
    free: 'ఉచితం',
    total: 'మొత్తం',
    payNow: 'ఇప్పుడు చెల్లించండి',
    welcomeBack: 'తిరిగి స్వాగతం',
    signInSubtitle: 'మీ ఓట్‌బైట్స్ ఖాతాలో సైన్ ఇన్ చేయండి',
    emailAddress: 'ఇమెయిల్ చిరునామా',
    password: 'పాస్‌వర్డ్',
    signingIn: 'సైన్ ఇన్ అవుతోంది...',
    or: 'లేదా',
    continueWithGoogle: 'Google తో కొనసాగించండి',
    signUpWithGoogle: 'Google తో సైన్ అప్',
    noAccount: 'ఖాతా లేదా?',
    signUp: 'సైన్ అప్',
    createAccount: 'ఖాతా సృష్టించండి',
    createAccountSubtitle: 'షాపింగ్ ప్రారంభించడానికి ఓట్‌బైట్స్‌లో చేరండి',
    creatingAccount: 'ఖాతా సృష్టించబడుతోంది...',
    hasAccount: 'ఇప్పటికే ఖాతా ఉందా?',
    men: 'పురుషులు',
    women: 'మహిళలు',
    copyright: '© 2026 ఓట్‌బైట్స్ బై SEJ. అన్ని హక్కులు రిజర్వ్ చేయబడ్డాయి.',
    language: 'భాష',
  },
  mr: {
    aboutUs: 'आमच्याबद्दल',
    admin: 'अॅडमिन',
    signIn: 'साइन इन',
    dashboard: 'डॅशबोर्ड',
    signOut: 'साइन आउट',
    heroTitle: 'आरोग्यदायी आणि',
    heroTitle2: 'चविष्ट.',
    heroSubtitle: 'क्रंचचा अनुभव घ्या. प्रेम, काळजी आणि उत्कृष्ट सेंद्रिय घटकांनी बनवलेले प्रीमियम ओटबाइट्स.',
    shopNow: 'आता खरेदी करा',
    featuredOatbites: 'विशेष ओटबाइट्स',
    viewAllProducts: 'सर्व उत्पादने पहा',
    addToCart: 'कार्टमध्ये जोडा',
    inCart: 'कार्टमध्ये',
    customer: 'ग्राहक',
    yourOrders: 'तुमचे ऑर्डर',
    noOrders: 'तुम्ही अजून कोणतीही ऑर्डर दिलेली नाही.',
    startShopping: 'खरेदी सुरू करा',
    editProfile: 'प्रोफाइल संपादित करा',
    saveChanges: 'बदल जतन करा',
    saving: 'जतन करत आहे...',
    profileUpdated: 'प्रोफाइल यशस्वीरित्या अपडेट झाले!',
    phone: 'फोन नंबर',
    address: 'पत्ता',
    name: 'पूर्ण नाव',
    email: 'ईमेल',
    cancel: 'रद्द करा',
    products: 'उत्पादने',
    searchProducts: 'उत्पादने शोधा...',
    allProducts: 'सर्व उत्पादने',
    outOfStock: 'स्टॉकमध्ये नाही',
    checkout: 'चेकआउट',
    shippingDetails: 'शिपिंग तपशील',
    fullName: 'पूर्ण नाव',
    streetAddress: 'रस्त्याचा पत्ता',
    city: 'शहर',
    state: 'राज्य',
    pincode: 'पिनकोड',
    orderSummary: 'ऑर्डर सारांश',
    subtotal: 'उपएकूण',
    shipping: 'शिपिंग',
    free: 'मोफत',
    total: 'एकूण',
    payNow: 'आता पेमेंट करा',
    welcomeBack: 'पुन्हा स्वागत',
    signInSubtitle: 'तुमच्या ओटबाइट्स खात्यात साइन इन करा',
    emailAddress: 'ईमेल पत्ता',
    password: 'पासवर्ड',
    signingIn: 'साइन इन होत आहे...',
    or: 'किंवा',
    continueWithGoogle: 'Google सह सुरू ठेवा',
    signUpWithGoogle: 'Google सह साइन अप',
    noAccount: 'खाते नाही?',
    signUp: 'साइन अप',
    createAccount: 'खाते तयार करा',
    createAccountSubtitle: 'खरेदी सुरू करण्यासाठी ओटबाइट्स जॉइन करा',
    creatingAccount: 'खाते तयार होत आहे...',
    hasAccount: 'आधीच खाते आहे?',
    men: 'पुरुष',
    women: 'महिला',
    copyright: '© 2026 ओटबाइट्स बाय SEJ. सर्व हक्क राखीव.',
    language: 'भाषा',
  },
};

const LANGUAGE_NAMES = {
  en: 'English',
  hi: 'हिन्दी',
  bn: 'বাংলা',
  ta: 'தமிழ்',
  te: 'తెలుగు',
  mr: 'मराठी',
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [locale, setLocale] = useState('en');

  useEffect(() => {
    const saved = localStorage.getItem('ob_lang');
    if (saved && translations[saved]) {
      setLocale(saved);
    }
  }, []);

  const changeLanguage = (lang) => {
    setLocale(lang);
    localStorage.setItem('ob_lang', lang);
  };

  const t = (key) => {
    return translations[locale]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ locale, changeLanguage, t, LANGUAGE_NAMES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
